language: scala
jdk: openjdk8
scala: 2.12.7

jobs:
  include:
    - stage: test
      script: sbt scalafmtCheck scalafmtSbtCheck
      name: "Formatting check"
    - script: sbt ";^test ;^scripted"
      name: "Tests run"
    - stage: publish
      script: sbt ";^publish"
      name: "Publish"

stages:
  - name: test # runs on master commits and PRs
    if: NOT tag =~ ^v
  - name: publish # runs on main repo master commits or version-tagged commits
    if: repo = lightbend/sbt-paradox-project-info AND ( ( branch = master AND type = push ) OR tag =~ ^v )

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never

env:
  global:
    # travis encrypt --com BINTRAY_USER=...
    - secure: "oQkE8gjTzGV/au2KPUg3FEuidVU/hxGSwt54YuXMhppkpqJzXuheACF3BTE4yvbKGyp7nOeddOQRb+k8PE+AencYFANmVVoGgdqJIM1CKzV/gPiWKcetkmIXpxBBizWLybaU20ip2l5sDBkC//ss80t8OjSTkyaONvctOTLFE1ntUcpqySTcPZogtFrq0mSEgqdn2pCgq4l/1gsbOrvsPMa5KqLH5p3mLnx+kO0Oof+lJKzHoCHF3vYU7mxcYZIiLj7sVoKVIJmgppAw+QNlEDm+BBIGFWr5z9zZEK87rZDpmHoZfvqrjefSiJqURZ53kPzo2vJOy9tKzRLVhYkk4KFxkXDlG0B5pN+dT8Tmg9e3LAYVv51nt/A/hRoMSuTonukK4oMi2TME6730UgFy4Dn4CK+/G7yw5xNmx2pQflEqgCABNzwrCJz4BmUlHrmPVtvOKH9Rg3LWWwab3zxfeTIt01WqZudzIw4PpgS8FTBZHr0p3EHL4gFjwf/gYBB47SSio3GUCfQnHUqDrqYNeC4wsEG+aKMRkRP8ZMGDsLiMpWpb+aw2M98YogDwumbx/xgv2Gqp/ql3Yvzs8c6Z2QLTC2RVRxiiWdErSC9v2YIp+Lp6tC7VUgKhcQ//R1f5TX1Po3pVaFARQ8veb80beFXsQfPjB0DgsFXSJOUD68Y="
    # travis encrypt --com BINTRAY_PASS=...
    - secure: "B2rNA4s+dbXYcJFbwGHYD7JoUhefLAsuY8FJzSIZwVFKaYthWgwTtwkXJsd/obteIAJyabUR79XDL8Lc3xnMByO6YVw44cq/0kftIDHotyfZxzy1I4mj6g2SKgF3xWOWV8HT12I03rm9QAyU0ooE7WCO08XgsY7PQxLRKzzvv/l/8GN/i//sy9HKZ6tw6flVISsjsUAx5c4NaK0ieawLxDKq6ncndvqFLIc8z0d0r7hpK2hJfwzKMeeFh71aVu6Jf5amcxDkQHvHrS5zGPUqp2uk538yt+KHVbaYxU7/76PrAx54YxSJoys6XIY2e5NfuLGXzV17MJclh2fA9tVg0L+0K8kHW/E9fIhRfGCbZFuciqWOHO1tz5jzynxPuval/5sWGhxy/Fpw1ammS/HmLWLEGs3SvOwAceud4GVW6gF7LNtpe7b2yXWXE1Od4qKsq3nZlmjBFyIRvQ8K/+gxfHygobS6VMTdMtjIC7FhDIAXNiNyDLt6bUjiAK0Dm5P7rCf+cZmDLOfYWbdnmWf5eOcz835T3aswCLwpQ/yNOBUR0jeLXYmHctl8PxDe6QSCodhfwPVwRnnjMQf9roD2EhFtkhCwPl1Yxmrl/cajqHXDFJ9z3TwXvOFOZwqZJ83LcWUrBxvUQZ3W/W5TxlxRk5Cw59ee+WGMAq8rRarVBaM="
